---
-
  hosts: all
  sudo: true
  tasks:
    -
      name: "update serveur"
      apt: 
        update_cache: yes
        upgrade: full
    -
      name: "Instalaltion des programmes"
      apt: 
        name: 
          - curl
          - gnupg2
          - apt-transport-https
          - ca-certificates
          - software-properties-common
    -
      name: Add an Apt signing key, uses whichever key is at the URL
      apt_key: "url=https://download.docker.com/linux/debian/gpg validate_certs=no"

    - 
      name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian jessie stable
    - 
      name: "Installation Docker"
      apt: 
        name: 
          - docker-ce
     -
      name: "Add User"
      user: 
        name: vagrant
        comment: Vagrant
        group: docker 
