---
-
  hosts: all
  sudo: true
  tasks:
    -
      name: "update serveur"
      apt: 
        update_cache: yes
        upgrade: full
    -
      name: "Instalaltion des programmes"
      apt: 
        name: 
          - curl
          - gnupg2
          - apt-transport-https
          - ca-certificates
          - software-properties-common
    -
      name: Add an Apt signing key, uses whichever key is at the URL
      apt_key: "url=https://download.docker.com/linux/debian/gpg validate_certs=no"

    - 
      name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian jessie stable
    - 
      name: "Installation Docker"
      apt: 
        name: 
          - docker-ce
    -
      name: "Add User"
      user: 
        name: vagrant
        comment: Vagrant
        group: docker 
    - 
      name: "Charger le script d'ajout des packages de gitlab-runner"
      get_url: "url=https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh dest=/opt mode=755"
    - 
      name: "Executer le script"
      command: /opt/script.deb.sh
    - 
      name: "Installer gitlab-runner"
      apt: 
        name: gitlab-runner
    - 
      name: "CrÃ©ation Runner"
      loop:
        - { name: 'Runner 1', image: 'java:latest', tags: 'java, docker, intm, Debian' }
        - { name: 'Runner 2', image: 'java:latest', tags: 'java, docker, intm, Debian' }
        - { name: 'Runner 3', image: 'java:latest', tags: 'java, docker, intm, Debian' }
        - { name: 'Runner 4', image: 'java:latest', tags: 'java, docker, intm, Debian' }
        - { name: 'Runner 5', image: 'java:latest', tags: 'java, docker, intm, Debian' }
        - { name: 'Runner 6', image: 'java:latest', tags: 'java, docker, intm, Debian' }
      shell: >
        sudo gitlab-runner register
        --non-interactive 
        --url "https://{{ip}}/" 
        --executor "docker" 
        --name "{{ item.name }}" 
        --registration-token {{token}} 
        --docker-image {{ item.image }} \
        --tag-list "{{ item.tags }}" 
        --run-untagged="true" 
        --locked="false" 
        --access-level="not_protected"
      
