--- 
- 
  hosts: all
  sudo: true
  tasks: 
    - 
      apt: name=tree
      name: "Installation du paquet TREE pour la beaut√©"
    - 
      name: "update serveur"
      apt:
        update_cache: yes
        upgrade: full
